repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.0    # placeholder
    hooks:
      - id: ruff
        args: [--fix]
        exclude: '\.ipynb$'
      - id: ruff-format
        exclude: '\.ipynb$'
  - repo: https://github.com/kynan/nbstripout
    rev: 0.9.1
    hooks:
      - id: nbstripout